from PyPDF2 import PdfReader, PdfWriter

writer = PdfWriter()
reader = PdfReader("PHB2024.pdf")
writer.append_pages_from_reader(reader)

PAGE_OFFSET = 2

welcome = writer.add_outline_item("Welcome to Adventure", 4 - PAGE_OFFSET)
writer.add_outline_item("What You Need", 4 - PAGE_OFFSET, welcome)
writer.add_outline_item("Using This Book", 5 - PAGE_OFFSET, welcome)
writer.add_outline_item("Worlds of Adventure", 5 - PAGE_OFFSET, welcome)

c1 = writer.add_outline_item("Chapter 1: Playing the Game", 6 - PAGE_OFFSET)
writer.add_outline_item("Player or DM?", 7 - PAGE_OFFSET, c1)
writer.add_outline_item("Rhythm of Play", 8 - PAGE_OFFSET, c1)
writer.add_outline_item("An Ongoing Game", 8 - PAGE_OFFSET, c1)
writer.add_outline_item("Dice", 9 - PAGE_OFFSET, c1)
writer.add_outline_item("The Six Abilities", 10 - PAGE_OFFSET, c1)
tests = writer.add_outline_item("D20 Tests", 10 - PAGE_OFFSET, c1)
writer.add_outline_item("Ability Checks", 10 - PAGE_OFFSET, tests)
writer.add_outline_item("Saving Throws", 11 - PAGE_OFFSET, tests)
writer.add_outline_item("Attack Rolls", 12 - PAGE_OFFSET, tests)
writer.add_outline_item("Advantage/Disadvantage", 12 - PAGE_OFFSET, tests)
writer.add_outline_item("Proficiency", 13 - PAGE_OFFSET, c1)
actions = writer.add_outline_item("Actions", 15 - PAGE_OFFSET, c1)
writer.add_outline_item("Bonus Actions", 15 - PAGE_OFFSET, actions)
writer.add_outline_item("Reactions", 15 - PAGE_OFFSET, actions)
writer.add_outline_item("Social Interaction", 16 - PAGE_OFFSET, c1)
explo = writer.add_outline_item("Exploration", 19 - PAGE_OFFSET, c1)
writer.add_outline_item("Vision and Light", 19 - PAGE_OFFSET, explo)
writer.add_outline_item("Hiding", 19 - PAGE_OFFSET, explo)
writer.add_outline_item("Interacting with Objects", 19 - PAGE_OFFSET, explo)
writer.add_outline_item("Hazards", 20 - PAGE_OFFSET, explo)
writer.add_outline_item("Travel", 20 - PAGE_OFFSET, explo)
combat = writer.add_outline_item("Combat", 23 - PAGE_OFFSET, c1)
writer.add_outline_item("The Order of Combat", 23 - PAGE_OFFSET, combat)
writer.add_outline_item("Movement and Position", 24 - PAGE_OFFSET, combat)
writer.add_outline_item("Making an Attack", 25 - PAGE_OFFSET, combat)
writer.add_outline_item("Ranged Attacks", 26 - PAGE_OFFSET, combat)
writer.add_outline_item("Melee Attacks", 26 - PAGE_OFFSET, combat)
writer.add_outline_item("Mounted Combat", 26 - PAGE_OFFSET, combat)
writer.add_outline_item("Underwater Combat", 27 - PAGE_OFFSET, combat)
dmg = writer.add_outline_item("Damage and Healing", 27 - PAGE_OFFSET, c1)
writer.add_outline_item("Hit Points", 27 - PAGE_OFFSET, dmg)
writer.add_outline_item("Damage Rolls", 27 - PAGE_OFFSET, dmg)
writer.add_outline_item("Critical Hits", 27 - PAGE_OFFSET, dmg)
writer.add_outline_item("Saving Throws and Damage", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Damage Types", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Resistance and Vulnerability", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Immunity", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Healing", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Dropping to 0 Hit Points", 28 - PAGE_OFFSET, dmg)
writer.add_outline_item("Temporary Hit Points", 29 - PAGE_OFFSET, dmg)
writer.add_outline_item("Conditions", 29 - PAGE_OFFSET, c1)

c2 = writer.add_outline_item("Chapter 2: Creating a Character", 32 - PAGE_OFFSET)
writer.add_outline_item("Create Your Character", 33 - PAGE_OFFSET, c2)
writer.add_outline_item("Level Advancement", 41 - PAGE_OFFSET, c2)
writer.add_outline_item("Starting at Higher Levels", 43 - PAGE_OFFSET, c2)
writer.add_outline_item("Multiclassing", 44 - PAGE_OFFSET, c2)
writer.add_outline_item("Trinkets", 46 - PAGE_OFFSET, c2)

c3 = writer.add_outline_item("Chapter 3: Character Classes", 48 - PAGE_OFFSET)
barbarian = writer.add_outline_item("Barbarian", 50 - PAGE_OFFSET, c3)
writer.add_outline_item("Path of the Berserker", 54 - PAGE_OFFSET, barbarian)
writer.add_outline_item("Path of the Wild Heart", 55 - PAGE_OFFSET, barbarian)
writer.add_outline_item("Path of the World Tree", 56 - PAGE_OFFSET, barbarian)
writer.add_outline_item("Path of the Zealot", 57 - PAGE_OFFSET, barbarian)
bard = writer.add_outline_item("Bard", 58 - PAGE_OFFSET, c3)
writer.add_outline_item("Bard Spell List", 62 - PAGE_OFFSET, bard)
writer.add_outline_item("College of Dance", 64 - PAGE_OFFSET, bard)
writer.add_outline_item("College of Glamour", 65 - PAGE_OFFSET, bard)
writer.add_outline_item("College of Lore", 66 - PAGE_OFFSET, bard)
writer.add_outline_item("College of Valor", 67 - PAGE_OFFSET, bard)
cleric = writer.add_outline_item("Cleric", 68 - PAGE_OFFSET, c3)
writer.add_outline_item("Cleric Spell List", 71 - PAGE_OFFSET, cleric)
writer.add_outline_item("Life Domain", 73 - PAGE_OFFSET, cleric)
writer.add_outline_item("Light Domain", 74 - PAGE_OFFSET, cleric)
writer.add_outline_item("Trickery Domain", 75 - PAGE_OFFSET, cleric)
writer.add_outline_item("War Domain", 76 - PAGE_OFFSET, cleric)
druid = writer.add_outline_item("Druid", 78 - PAGE_OFFSET, c3)
writer.add_outline_item("Druid Spell List", 82 - PAGE_OFFSET, druid)
writer.add_outline_item("Circle of the Land", 84 - PAGE_OFFSET, druid)
writer.add_outline_item("Circle of the Moon", 86 - PAGE_OFFSET, druid)
writer.add_outline_item("Circle of the Sea", 87 - PAGE_OFFSET, druid)
writer.add_outline_item("Circle of the Stars", 88 - PAGE_OFFSET, druid)
fighter = writer.add_outline_item("Fighter", 90 - PAGE_OFFSET, c3)
writer.add_outline_item("Battle Master", 93 - PAGE_OFFSET, fighter)
writer.add_outline_item("Champion", 96 - PAGE_OFFSET, fighter)
writer.add_outline_item("Eldritch Knight", 96 - PAGE_OFFSET, fighter)
writer.add_outline_item("Psi Warrior", 98 - PAGE_OFFSET, fighter)
monk = writer.add_outline_item("Monk", 100 - PAGE_OFFSET, c3)
writer.add_outline_item("Warrior of Mercy", 104 - PAGE_OFFSET, monk)
writer.add_outline_item("Warrior of Shadow", 105 - PAGE_OFFSET, monk)
writer.add_outline_item("Warrior of the Elements", 106 - PAGE_OFFSET, monk)
writer.add_outline_item("Warrior of the Open Hand", 107 - PAGE_OFFSET, monk)
paladin = writer.add_outline_item("Paladin", 108 - PAGE_OFFSET, c3)
writer.add_outline_item("Paladin Spell List", 112 - PAGE_OFFSET, paladin)
writer.add_outline_item("Oath of Devotion", 113 - PAGE_OFFSET, paladin)
writer.add_outline_item("Oath of Glory", 114 - PAGE_OFFSET, paladin)
writer.add_outline_item("Oath of the Ancients", 115 - PAGE_OFFSET, paladin)
writer.add_outline_item("Oath of Vengeance", 116 - PAGE_OFFSET, paladin)
ranger = writer.add_outline_item("Ranger", 118 - PAGE_OFFSET, c3)
writer.add_outline_item("Ranger Spell List", 121 - PAGE_OFFSET, ranger)
writer.add_outline_item("Beast Master", 122 - PAGE_OFFSET, ranger)
writer.add_outline_item("Fey Wanderer", 124 - PAGE_OFFSET, ranger)
writer.add_outline_item("Gloom Stalker", 125 - PAGE_OFFSET, ranger)
writer.add_outline_item("Hunter", 127 - PAGE_OFFSET, ranger)
rogue = writer.add_outline_item("Rogue", 128 - PAGE_OFFSET, c3)
writer.add_outline_item("Arcane Trickster", 132 - PAGE_OFFSET, rogue)
writer.add_outline_item("Assassin", 134 - PAGE_OFFSET, rogue)
writer.add_outline_item("Soulknife", 135 - PAGE_OFFSET, rogue)
writer.add_outline_item("Thief", 137 - PAGE_OFFSET, rogue)
sorcerer = writer.add_outline_item("Sorcerer", 138 - PAGE_OFFSET, c3)
writer.add_outline_item("Metamagic Options", 141 - PAGE_OFFSET, sorcerer)
writer.add_outline_item("Sorcerer Spell List", 142 - PAGE_OFFSET, sorcerer)
writer.add_outline_item("Aberrant Sorcery", 145 - PAGE_OFFSET, sorcerer)
writer.add_outline_item("Clockwork Sorcery", 146 - PAGE_OFFSET, sorcerer)
writer.add_outline_item("Draconic Sorcery", 148 - PAGE_OFFSET, sorcerer)
writer.add_outline_item("Wild Magic Sorcery", 149 - PAGE_OFFSET, sorcerer)
warlock = writer.add_outline_item("Warlock", 152 - PAGE_OFFSET, c3)
writer.add_outline_item("Eldritch Invocation Options", 155 - PAGE_OFFSET, warlock)
writer.add_outline_item("Warlock Spell List", 157 - PAGE_OFFSET, warlock)
writer.add_outline_item("Archfey Patron", 159 - PAGE_OFFSET, warlock)
writer.add_outline_item("Celestial Patron", 160 - PAGE_OFFSET, warlock)
writer.add_outline_item("Fiend Patron", 161 - PAGE_OFFSET, warlock)
writer.add_outline_item("Great Old One Patron", 162 - PAGE_OFFSET, warlock)
wizard = writer.add_outline_item("Wizard", 164 - PAGE_OFFSET, c3)
writer.add_outline_item("Wizard Spell List", 168 - PAGE_OFFSET, wizard)
writer.add_outline_item("Abjurer", 172 - PAGE_OFFSET, wizard)
writer.add_outline_item("Diviner", 173 - PAGE_OFFSET, wizard)
writer.add_outline_item("Evoker", 174 - PAGE_OFFSET, wizard)
writer.add_outline_item("Illusionist", 175 - PAGE_OFFSET, wizard)

c4 = writer.add_outline_item("Chapter 4: Character Origins", 176 - PAGE_OFFSET)
writer.add_outline_item("Origin Components", 177 - PAGE_OFFSET, c4)
backgrounds = writer.add_outline_item("Background Descriptions", 177 - PAGE_OFFSET, c4)
writer.add_outline_item("Acolyte", 178 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Artisan", 178 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Charlatan", 179 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Criminal", 179 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Entertainer", 180 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Farmer", 180 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Guard", 181 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Guide", 181 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Hermit", 182 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Merchant", 182 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Noble", 183 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Sage", 183 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Sailor", 184 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Scribe", 184 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Soldier", 185 - PAGE_OFFSET, backgrounds)
writer.add_outline_item("Wayfarer", 185 - PAGE_OFFSET, backgrounds)
species = writer.add_outline_item("Species Descriptions", 186 - PAGE_OFFSET, c4)
writer.add_outline_item("Aasimar", 186 - PAGE_OFFSET, species)
writer.add_outline_item("Dragonborn", 187 - PAGE_OFFSET, species)
writer.add_outline_item("Dwarf", 188 - PAGE_OFFSET, species)
writer.add_outline_item("Elf", 189 - PAGE_OFFSET, species)
writer.add_outline_item("Gnome", 191 - PAGE_OFFSET, species)
writer.add_outline_item("Goliath", 192 - PAGE_OFFSET, species)
writer.add_outline_item("Halfling", 193 - PAGE_OFFSET, species)
writer.add_outline_item("Human", 194 - PAGE_OFFSET, species)
writer.add_outline_item("Orc", 195 - PAGE_OFFSET, species)
writer.add_outline_item("Tiefling", 196 - PAGE_OFFSET, species)

c5 = writer.add_outline_item("Chapter 5: Feats", 198 - PAGE_OFFSET)
writer.add_outline_item("Feat Descriptions", 199 - PAGE_OFFSET, c5)
writer.add_outline_item("Origin Feats", 200 - PAGE_OFFSET, c5)
writer.add_outline_item("General Feats", 202 - PAGE_OFFSET, c5)
writer.add_outline_item("Fighting Style Feats", 209 - PAGE_OFFSET, c5)
writer.add_outline_item("Epic Boon Feats", 210 - PAGE_OFFSET, c5)

c6 = writer.add_outline_item("Chapter 6: Equipment", 212 - PAGE_OFFSET)
writer.add_outline_item("Coins", 213 - PAGE_OFFSET, c6)
weapons = writer.add_outline_item("Weapons", 213 - PAGE_OFFSET, c6)
writer.add_outline_item("Properties", 213 - PAGE_OFFSET, weapons)
writer.add_outline_item("Mastery Properties", 214 - PAGE_OFFSET, weapons)
writer.add_outline_item("Armor", 219 - PAGE_OFFSET, c6)
writer.add_outline_item("Tools", 220 - PAGE_OFFSET, c6)
writer.add_outline_item("Adventuring Gear", 222 - PAGE_OFFSET, c6)
writer.add_outline_item("Mounts and Vehicles", 229 - PAGE_OFFSET, c6)
writer.add_outline_item("Services", 230 - PAGE_OFFSET, c6)
writer.add_outline_item("Magic Items", 232 - PAGE_OFFSET, c6)
writer.add_outline_item("Crafting Equipment", 233 - PAGE_OFFSET, c6)

c7 = writer.add_outline_item("Chapter 7: Spells", 234 - PAGE_OFFSET)
writer.add_outline_item("Gaining Spells", 235 - PAGE_OFFSET, c7)
writer.add_outline_item("Casting Spells", 235 - PAGE_OFFSET, c7)
writer.add_outline_item("Spell Descriptions", 239 - PAGE_OFFSET, c7)

appA = writer.add_outline_item("Appendix A: The Multiverse", 344 - PAGE_OFFSET)
writer.add_outline_item("The Material Realms", 344 - PAGE_OFFSET, appA)
writer.add_outline_item("Transitive Planes", 344 - PAGE_OFFSET, appA)
writer.add_outline_item("The Inner Planes", 344 - PAGE_OFFSET, appA)
writer.add_outline_item("The Outer Planes", 344 - PAGE_OFFSET, appA)

writer.add_outline_item("Appendix B: Creature Stat Blocks", 346 - PAGE_OFFSET)

writer.add_outline_item("Appendix C: RUles Glossary", 360 - PAGE_OFFSET)

writer.add_outline_item("Index", 378 - PAGE_OFFSET)


writer.write("PHB2024_chaptered.pdf")